//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnologyDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnologyTable
    {
        public int SNO { get; set; }
        public string LanguageName { get; set; }
        public string TutorialName { get; set; }
        public string YoutubeLink { get; set; }
    }
}
